### ISSUE TITLE
Create Table of Contenets

### ISSUE THREAD

**Issue by Agrover112** [Agrover112/awesome-semantic-search#15]
Create a **Table of Contents.**
with headings : Papers,  Libraries&Tools , Datasets ,etc.
Refer following repo for format:  https://github.com/akullpp/awesome-java#jvm-and-jdk

**Comment by krishdevdb** [comment]
Can I Do It

**Comment by Agrover112** [comment]
@krishdevdb  Sure take it up

**Comment by krishdevdb** [comment]
Done #16
