### ISSUE TITLE
Docs: Add Issue templates

### ISSUE THREAD

**Issue by vinzvinci** [Agrover112/awesome-semantic-search#18]
It will be cool if you add issue templates, cause it's very important if there are new contributors, so they know what to follow.

**Comment by Agrover112** [comment]
Do you want to raise an PR?

**Comment by Vyvy-vi** [comment]
related to #17

**Comment by vinzvinci** [comment]
Hi @Agrover112, I think it's better if you put this in our EddieHub community #good-first-issues channel.

**Comment by Agrover112** [comment]
> Hi @Agrover112, I think it's better if you put this in our EddieHub community #good-first-issues channel.

I think I added a few templates . I will add them if anything else is needed?

**Comment by vinzvinci** [comment]
Yeah up to you, I suggest creating for bug, features, and etc. issue templates.
