### ISSUE TITLE
Remove Table of Contents

### ISSUE THREAD

**Issue by Vyvy-vi** [Agrover112/awesome-semantic-search#19]
### Description
Github automatically renders a Table Of Contents on the README.md file.
Rather than using typing out a Table of Contents, using the default Table might help in making the README more succint and brief

### Screenshot
![Screenshot 2021-05-14 at 11 08 17 PM](https://user-images.githubusercontent.com/62864373/118308233-55939300-b509-11eb-9c9b-9ffbcef74ea4.png)

**Comment by Agrover112** [comment]
Awesome list's can become large so I believe this  is need this for the markdown explicitly.
