### ISSUE TITLE
[BUG] 2021/2022 paper - broken link - page not found

### ISSUE THREAD

**Issue by meenal21** [Agrover112/awesome-semantic-search#33]
**Describe the bug**
Paper mentioned under 2021/2022 section refers to a page not found.

**To Reproduce**
1. Go to Read.Me
2. Click on Learning Personal Style from Few Examples
3. See error - you will be taken to the page with 404 error

**Expected behavior**
Expected to see a paper containing Learning Personal Style from Few Examples.

**Screenshots**
![issue](https://user-images.githubusercontent.com/13515337/119256531-be9c9a00-bbde-11eb-8641-e8cffa1ea134.PNG)

**Comment by Agrover112** [comment]
The following paper is in the pipelines for acceptance to a particular Conference.
