### ISSUE TITLE
Create Sections for Audio ,Video, Image/ Multimodal

### ISSUE THREAD

**Issue by Agrover112** [Agrover112/awesome-semantic-search#4]
Sub-categorize papers into Text/Speech/Image/Video/Multimodal.
This can be done by adding a special colour beside the paper or the paper to indicate the paper modality.

**Comment by meenal21** [comment]
Hi @Agrover112,

In place of special color, we could also add emojis to specify the modality, which would reduce the need to refer to the color table:

Video - :film_projector: , 
Speech - :sound:,
Text - 📄 
Image - :camera:
Multimodal - we could add the symbols according to the modals present in the paper.

Please let me know if this looks good.

**Comment by Agrover112** [comment]
Sure sounds like a good idea

**Comment by meenal21** [comment]
I have now symbol marked the papers, however, there were few papers that were a general fit. I have not assigned any symbol to them yet. I am raising a PR for the same.
